### ISSUE TITLE
Popup of planes not updating new position when label dragged

### ISSUE THREAD

**Issue by opheliaprillard22** [SINTEF/SESAR-CWP#105]
- The second popups (change level, bearing, etc.) stay in original place after plane is dragged

**Comment by fungiboletus** [comment]
Yes, is it a must to implement it ? 😄

**Comment by opheliaprillard22** [comment]
I don't know, but I think so! If they play around and then want to make changes, they probably will not drag it back to its place 🗡️ and then it looks weird
