### ISSUE TITLE
Adding the possibility to remove/cancel aircrafts

### ISSUE THREAD

**Issue by opheliaprillard22** [SINTEF/SESAR-CWP#178]
Giuseppe would like to be able to cancel flight in MASTER- mode, since there will be so many planes during the exercise. 
- [x] Adding remove button to flight label only in Master mode - probably next to cross to hide label
- [x] "Deleting" aircraft

**Comment by fungiboletus** [comment]
"Deleting" aircraft, such as hiding them ? I'm not sure we can easily tell the simulator to delete them.

**Comment by opheliaprillard22** [comment]
Yes hiding is fine

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Antoine Pultier ***@***.***>
Sendt: Wednesday, September 21, 2022 8:06:11 PM
Til: SINTEF/SESAR-CWP ***@***.***>
Kopi: Ophelia Prillard ***@***.***>; Author ***@***.***>
Emne: Re: [SINTEF/SESAR-CWP] Adding the possibility to remove/cancel aircrafts (Issue #178)


"Deleting" aircraft, such as hiding them ? I'm not sure we can easily tell the simulator to delete them.

**Comment by fungiboletus** [comment]
That's a rather big feature to implement in such a short time. Is it critical or can we skip it?
