### ISSUE TITLE
Flight label should start from middle of airplane icon

### ISSUE THREAD

**Issue by opheliaprillard22** [SINTEF/SESAR-CWP#180]
- Are you able to make the label draggable line start on the airplane icon? In the middle

**Comment by fungiboletus** [comment]
Yeah, I actually spent some efforts to not make it start from the middle because I believe it looks bad and reduces the readability of the airplane icons. But this code could be removed.

**Comment by opheliaprillard22** [comment]
Yes, sorry, but that was one of the comments yesterday during testing that he wanted it from the middle
