### ISSUE TITLE
Remove loading choose controller? Show only master if no message given?

### ISSUE THREAD

**Issue by opheliaprillard22** [SINTEF/SESAR-CWP#185]
We are the ones who are going to choose the CWPs anyway and it could be that we have not gotten any messages perhaps and want to test with master controller only. @fungiboletus  what do you think?

**Comment by fungiboletus** [comment]
How are you going to select the controller then?

**Comment by opheliaprillard22** [comment]
I mean just the loading part, not the whole thing. That is it loading while we are awaiting for assignment-messages, but we could actually choose "Master" without needing who has which sector

**Comment by fungiboletus** [comment]
Oh I see. I think it's important that we can see that the data is loading, but the master button could be displayed from the start.

**Comment by opheliaprillard22** [comment]
Yes! Good idea
