### ISSUE TITLE
Implement floating sector configuration

### ISSUE THREAD

**Issue by fungiboletus** [SINTEF/SESAR-CWP#24]
- [x] Connect it with availability messages
- [x] Add current and next sector configurations
- [x] How to make the draggable component with split screen (can only be dragged to the other screens, but not from) 
- [ ] Making those spanning few FL be smallere than those spanning more FLs
- [x] Adding border on selected item

**Comment by fungiboletus** [comment]
@opheliaprillard22 Is "Filling the whole square when grid css does not take float values" done?

**Comment by opheliaprillard22** [comment]
It's not really a problem at least anymore. They didn't care if it didn't fill the whole line. But there is the problem that the height is not also based on how many flightlevels it spans.
